//Hard coded data header

#ifndef __HARD_CODED_DATA_H__
#define __HARD_CODED_DATA_H__

//Defines:
#define SERVER_ADDRESS "127.0.0.1"
#define DEFAULT_TIMEOUT 15000
#define NUM_OF_DIGITS 4


//Typedefs:
//All of the main functions return a status enum for debugging
typedef enum _status {
    INVALID_STATUS_CODE = -1,
    SUCCESS = 0,
    WRONG_ARGUMENT_COUNT,
    INVALID_PORT_NUMBER,
    WSASTARTUP_FAILED,
    FAILED_TO_CREATE_SOCKET,
    FAILED_TO_CREATE_MUTEX,
    FAILED_TO_CONVERT_IP_ADDRESS,
    FAILED_TO_BIND_SOCKET,
    FAILED_TO_LISTEN_ON_SOCKET,
    FAILED_TO_CLOSE_SOCKET,
    FAILED_TO_ACCEPT_SOCKET,
    FAILED_TO_SET_SOCKET_OPT,
    FAILED_TO_CREATE_EVENT,
    FAILED_TO_SET_EVENT,
    FAILED_TO_CREATE_THREAD,
    FAILED_TO_WAIT,
    QUEUE_USER_APC_FAILED,
    FAILED_TO_SEND_STRING,
    FAILED_TO_RECIEVE_STRING,
    FAILED_TO_REMOVE_FILE,
    UNRELEASED_MUTEX,
    FOPEN_FAIL,
    ALLOC_FAILED,
} Status;


#endif